version: '3'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - '5173:5173'
    environment:
      - NODE_ENV=development
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - '8000:8000'
    env_file:
      - backend/.env
  db:
    image: postgres:16-alpine
    ports:
      - 5432:5432
    expose:
      - 5432
    env_file:
      - backend/.env
    volumes:
      - db_data:/var/lib/postgresql/data
  redis:
    image: redis:6
    volumes:
      - redis_data:/data

volumes:
  redis_data:
  db_data:
